/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0383d5408f215e69f925eb14a7450ee2)
interface __BaseEnv_Env {
	TIMELINE_OS: R2Bucket;
	TIMELINE_DB: D1Database;
	ASSETS: Fetcher;
	TIMELINE_ROOT_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TIMELINE_ROOT_TOKEN">> {}
}
